#!/usr/bin/env bash
# Script to update /etc/hosts so that localhost resolves to 127.0.0.2 and facebook.com to 8.8.8.8

(
    grep -v -E "localhost|facebook.com" /etc/hosts
    echo "127.0.0.2    localhost"
    echo "8.8.8.8      facebook.com"
) | sudo tee /etc/hosts > /dev/null
