#!/usr/bin/env bash
# Script to update /etc/hosts so that localhost resolves to 127.0.0.2 and facebook.com to 8.8.8.8

sudo sed -i.bak '/localhost/d' /etc/hosts
sudo sed -i.bak '/facebook.com/d' /etc/hosts

echo "127.0.0.2    localhost" | sudo tee -a /etc/hosts > /dev/null
echo "8.8.8.8      facebook.com" | sudo tee -a /etc/hosts > /dev/null
